### PR TITLE
TypeScript declarations

### LINKED ISSUE #13: Typescript Support?
Any plans for typescript supports? Would love to see it here :)

### PR DESCRIPTION
**Pull request by E-gy**
Closes #13.

This PR provides TypeScript declarations in `src`. At is it does not attempt to publish them to `dist` atm, as the question on _how to_ remains open.

See, since the declarations are manually written (as `.d.ts`), typescript compiler _does not check them_ - as in does not emit declarations for declarations on compilation.

One possible solution (and a better one, imho, perhaps just because i'm more used to TS) is to
1. Merge the JavaScript `.js` and type declarations `.d.ts` into TypeScript `.ts` files
2. Use `@babel/preset-typescript` in combination with `@babel/preset-env` to transpile into JS
3. Use `tsc` with `emitDeclarationOnly` to verify & emit type declarations
(axios has type declarations itself; `axios-token-interceptor` has type definitions in [`@types`](https://www.npmjs.com/package/@types/axios-token-interceptor))

This however effectibely converts the package into being written in TS, which may or may not be desired 🤷‍♂️.

The other possible solution is to simply copy all `.d.ts` files into `dist` on `build`.

### CODE REVIEW

**Review by compwright — CHANGES_REQUESTED** [review]
@E-gy thank you so much for stepping up to take care of this!

You've got some really long lines, can you update this to keep lines under 100 chars long wherever possible?

I'll research what build process changes need to be done to include these types. If you have any suggestions or good examples that would be greatly appreciated.

**Comment by bencelaszlo** [comment]
@compwright is there any update/decision on this issue?

**Comment by E-gy** [comment]
Should i create a different edition of this PR, where the lib is essentially converted into TypeScript (so following the 1st proposed solution)?

**Comment by CarltonHenderson** [comment]
Why not do the simple copy for now? This package doesn't seem to change too often, so it's probably not too onerous to manually update the `.d.ts` files right? Here's how it could be done:

### package.json
```diff
-     "build": "babel src -d dist",
+     "build": "babel src -d dist --copy-files",
```

image

**Pull request closed without merging**
